export const currencies = [
  "USD",
  "EUR",
  "GBP",
  "JPY",
  "CAD",
  "AUD",
  "CHF",
  "CNY",
  "SEK",
  "NZD",
  "KRW",
  "SGD",
  "HKD",
  "NOK",
  "MXN",
  "INR",
  "RUB",
  "BRL",
  "ZAR",
  "AED",
  "BD",
];
export const companyTypes = [
  "Technology",
  "Finance",
  "Healthcare",
  "Retail",
  "Education",
  "Manufacturing",
  "Transportation",
  "Hospitality",
  "Entertainment",
  "Non-Profit",
  "Telecommunications",
  "Energy",
  "Consulting",
  "Media",
  "Government",
];
export const functions = [
  "Accounting/Audit",
  "Administrative",
  "Advertising",
  "Business Analyst",
  "Finance Analyst",
  "Data Analyst",
  "Science",
  "Customer Service",
  "Consulting",
  "Distribution",
  "Human Resource",
  "Legal",
  "Information Technology",
  "Marketing",
  "Public Relations",
  "Others",
];

export const educationOptions = [
  "Bachelor's Degree",
  "Master's Degree",
  "Doctorate",
  "Associate's Degree",
  "High School Diploma",
  "Certification",
  "Other",
];

export const keywordOptions = [
  "React",
  "Node.js",
  "JavaScript",
  "Python",
  "SQL",
  "UX/UI Design",
  "Agile",
  "Scrum",
  "Remote",
  "Hybrid",
  "Full Stack",
  "Frontend",
  "Backend",
  "DevOps",
];
export const employmentTypes = [
  "Full Time",
  "Part Time",
  "Contract",
  "Freelance",
  "Internship",
  "Temporary",
  "Volunteer",
  "Remote",
  "Hybrid",
  "Other",
];

export const experienceLevels = [
  "Entry Level",
  "Intermediate",
  "Senior",
  "Lead",
  "Manager",
  "Director",
];
